# Any copyright is dedicated to the Public Domain.
# http://creativecommons.org/publicdomain/zero/1.0/
#SET(PYTHON_BIN="/usr/bin/python")

#64 bit build
#SET(TCL_INCLUDE "c:/Tcl/include")
#SET(TCL_ARCHIVE "c:/Tcl/lib/tclstub85.lib")
IF (${CMAKE_SIZEOF_VOID_P} MATCHES 4)
SET (MINICONDA2 C:/Miniconda)
SET (MINICONDA3 C:/Miniconda36)
ELSE (${CMAKE_SIZEOF_VOID_P} MATCHES 4)
SET (MINICONDA2 C:/Miniconda-x64)
SET (MINICONDA3 C:/Miniconda36-x64)
ENDIF (${CMAKE_SIZEOF_VOID_P} MATCHES 4)

SET(TCL_INCLUDE "${MINICONDA2}/Library/include")
SET(TCL_ARCHIVE "${MINICONDA2}/Library/lib/tclstub86.lib")
SET(TCL_BIN     "${MINICONDA2}/Library/bin/tclsh.exe")
SET (PYTHON_ARCHIVE ${MINICONDA2}/libs/python27.lib)
SET (PYTHON_INCLUDE ${MINICONDA2}/include)
SET (PYTHON3_ARCHIVE ${MINICONDA3}/libs/python36.lib)
SET (PYTHON3_INCLUDE ${MINICONDA3}/include)

SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /fp:strict /EHsc")
SET (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /SAFESEH:NO")
SET (CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /SAFESEH:NO /NODEFAULTLIB:python3")
SET (CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} /SAFESEH:NO")

